### PR TITLE
Update on indonesian language

### PR DESCRIPTION
**Pull request by bopthoughts**
Its not finished. only 25% done

### CODE REVIEW

**Comment by Snake1999** [comment]
:+1: your work is great, I'll merge it after finished.

**Comment by icsmoke-mcpe** [comment]
I'll help to fill some word to translate for bahasa indonesia.

**Comment by Snake1999** [comment]
Maybe we should merge this first?

**Comment by karpovichv** [comment]
There's almost nothing to merge.

**Pull request closed without merging**
