### PR TITLE
Russian language.

### PR DESCRIPTION
**Pull request by Snake1999**
Much tired as me looking up my dictionary...

### CODE REVIEW

**Comment by Pub4Game** [comment]
The configuration you have translated in Google translator? :D

**Comment by Snake1999** [comment]
@Pub4Game Yes, i am new in Russian...

**Comment by Snake1999** [comment]
@Pub4Game Are you good at Russian? We'll welcome if you help us translating, instead of me :D

**Comment by Pub4Game** [comment]
Wow)) What languages do you know?

Yes, I know very well Russian language

**Comment by Snake1999** [comment]
@Pub4Game I've learned Chinese, Wenzhounese(:D), English, and i am learning Russian.
BTW, If you can help us translating, just send pull requests to https://github.com/Snake1999/Multi-language .

**Comment by Pub4Game** [comment]
Well, I will try to help you

**Comment by Snake1999** [comment]
@Pub4Game Good, and this will be merged after translation work finishes. Any problems got, gitter me  :D

**Comment by Pub4Game** [comment]
@Snake1999 Please read message in Gutter

**Comment by Pub4Game** [comment]
@Snake1999 You will have a english forum Nukkit?

**Comment by Snake1999** [comment]
Uhh... I won't, but our Nukkit team may have it build later.

By the way, about the Russian font, i have tested it in Linux rad hat enterprise and Windows 7. Here are what i get:

**Comment by Pub4Game** [comment]
It's weird! You have to start.bat, right? 

java-jar nukkit.jar

image

Winows 10

**Comment by Pub4Game** [comment]
noo....

**Comment by Snake1999** [comment]
Oops...

**Comment by Pub4Game** [comment]
@Snake1999 @MagicDroidX To display the Russian language to use the encoding "cp866"

```
java -Dfile.encoding=cp866 -jar nukkit-1.0-SNAPSHOT.jar
PAUSE 
```

image

**Pull request merged**
