### PR TITLE
I added polish translation.

### PR DESCRIPTION
**Pull request by grzegorz2047**

### CODE REVIEW

**Comment by wu-vincent** [comment]
Awesome! But would you mind to change `pl` to `pol`?

**Comment by grzegorz2047** [comment]
@MagicDroidX Ok, I'll change it.

**Comment by grzegorz2047** [comment]
@MagicDroidX OK, done.

**Comment by wu-vincent** [comment]
:D Well, you forgot the dictionary i think.

**Comment by wu-vincent** [comment]
*Directory

**Comment by grzegorz2047** [comment]
@MagicDroidX Hmm, right. Is it possible to change folder name using github web interface or do I have to change it manually on my pc?

**Comment by wu-vincent** [comment]
I think you have to use PC :/

**Comment by grzegorz2047** [comment]
@MagicDroidX I changed directory somehow xd

**Pull request merged**
